Create health condition for degraded status / quorum issues
k8ssandra/cass-operator pull request #360
Opened 2022-07-05 20:01 UTC by burmanm

**What this PR does**:
In case CassandraDatacenter is under some operation that degrades the cluster or QUORUM health check fails, update Condition on the Status to indicate this. This is to make user aware that certain other operations are not going to be successful.

**Which issue(s) this PR fixes**:
Fixes #<issue number>

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2022-07-05 21:11 UTC, jsanda commented on pkg/reconciliation/reconcile_racks.go
> +		updated = rc.setCondition(
If the cluster is degraded or unhealthy, should we just requeue?

2022-07-06 08:46 UTC, burmanm commented on pkg/reconciliation/reconcile_racks.go
> +		updated = rc.setCondition(
We already do that elsewhere, this is just to add the status (as I thought the DBPE-2283 wish was). If we requeue here, then we could never recover from the wrong status.

2022-07-10 03:09 UTC, jsanda requested changes

2022-07-10 03:09 UTC, jsanda commented on apis/cassandra/v1beta1/cassandradatacenter_types.go
> +	DatacenterHealthy        DatacenterConditionType = "Healthy"
Can you add some comments explaining this?

2022-07-12 13:42 UTC, jsanda approved these changes

2022-07-13 15:44 UTC, merged