Update tools, structure and Kubernetes version
k8ssandra/cass-operator pull request #533
Opened 2023-06-09 08:11 UTC by burmanm

**What this PR does**:
This is a subset of PR #524 , removing Kustomize v5 template changes

* Updates envtest base Kubernetes to 1.26
* Updates controller-runtime
* Fixes the flaky test
* Updates project structure to gov4-alpha, move controllers to different directory
* Regenerates and updates Mocks
* Improve testing quality by actually verifying all the Mocked method calls are done (and nothing extra)
* Adds more arch targets to Dockerfile

**Which issue(s) this PR fixes**:
Fixes #526
Fixes #531

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [ ] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2023-06-09 13:20 UTC, adejanovski requested changes
I have a small request for removing commented code.
Other than that, just waiting for failed checks to pass after re-running them.

2023-06-09 13:20 UTC, adejanovski commented on pkg/mocks/helper.go
> +	// return r0
```suggestion
```

Could we get rid of the commented lines if they're not used?

2023-06-09 13:20 UTC, adejanovski commented on pkg/mocks/helper.go
> +	// return r0
```suggestion
```

Same question here

2023-06-12 10:01 UTC, burmanm commented on pkg/mocks/helper.go
> +	// return r0
Done

2023-06-12 10:02 UTC, adejanovski approved these changes

2023-06-13 08:33 UTC, merged