Allow parallel restart of all already bootstrapped nodes
k8ssandra/cass-operator pull request #673
Opened 2024-07-08 16:00 UTC by burmanm

**What this PR does**:
If ``cassandra.datastax.com/allow-parallel-starts: true`` is set, the cass-operator will check first for all nodes that have previously bootstrapped but are down and then try to restart them.

This happens before we try to start any other node in the normal process.

**Which issue(s) this PR fixes**:
Fixes #646 

**Checklist**
- [ ] Changes manually tested
- [x] Automated Tests added/updated
- [ ] Documentation added/updated
- [x] CHANGELOG.md updated (not required for documentation PRs)
- [x] CLA Signed:  [DataStax CLA](https://cla.datastax.com/)

2024-07-09 14:55 UTC, adejanovski requested changes

2024-07-09 14:55 UTC, adejanovski commented on pkg/reconciliation/reconcile_racks.go
> +			notReady, err := rc.startNode(pod, false, endpointData)
**Issue:** We need a little more orchestration here to deal with the seed nodes. We need at least one seed up and running so that the subsequent nodes can start correctly.
I ran a test where I stopped a DC and then restarted it, and all pods got stuck on startup with the following error:
```
ERROR [main] 2024-07-09 11:58:35,569 CassandraDaemon.java:897 - Exception encountered during startup: The seed provider lists no seeds.
```

2024-07-09 19:49 UTC, burmanm commented on pkg/reconciliation/reconcile_racks.go
> +			notReady, err := rc.startNode(pod, false, endpointData)
Changed so that the fast path is skipped with the first node and normal seed processing is done.

2024-07-10 08:23 UTC, adejanovski approved these changes
Looks great. Could you take a look at the failing tests before merging?
Thanks!

2024-07-10 12:49 UTC, burmanm commented
Both failing tests are expected and one requires a fix in the mgmt-api (it's not cass-operator failure, but the fix is not released yet).

2024-07-10 12:49 UTC, merged